backend:
  name: git-gateway
  branch: main # ou master

media_folder: "src/assets"
public_folder: "/assets"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/index.md"
        label: "Home"
        name: "index"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
      - file: "src/research.md"
        label: "Research"
        name: "research"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
      - file: "src/teaching.md"
        label: "Teaching"
        name: "teaching"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
      - file: "src/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
      - file: "src/activities.md"
        label: "Activities"
        name: "activities"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
      - name: "settings"
        label: "Paramètres"
        delete: false
        editor:
        preview: false
        files:
        - name: "general"
          label: "Infos & Réseaux Sociaux"
          file: "src/_data/site.json" # Fichier où seront sauvegardées les données
          fields:
            - { label: "Adresse E-mail", name: "email", widget: "string" }
            - { label: "Lien GitHub", name: "github", widget: "string", required: false }
            - { label: "Lien LinkedIn", name: "linkedin", widget: "string", required: false }
            - { label: "Lien Twitter / X", name: "twitter", widget: "string", required: false }
    
